// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultiBillGenerator.Data;

#nullable disable

namespace MultiBillGenerator.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260404055414_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("MultiBillGenerator.Models.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BillDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Discount")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Tax")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("MultiBillGenerator.Models.BillItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BillId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.ToTable("BillItems");
                });

            modelBuilder.Entity("MultiBillGenerator.Models.CatalogItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CatalogItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "entrance",
                            CreatedAt = new DateTime(2026, 4, 4, 5, 54, 12, 437, DateTimeKind.Utc).AddTicks(6131),
                            Name = "Adult Ticket",
                            Price = 500m,
                            UpdatedAt = new DateTime(2026, 4, 4, 5, 54, 12, 437, DateTimeKind.Utc).AddTicks(6133)
                        },
                        new
                        {
                            Id = 2,
                            Category = "entrance",
                            CreatedAt = new DateTime(2026, 4, 4, 5, 54, 12, 437, DateTimeKind.Utc).AddTicks(6136),
                            Name = "Child Ticket",
                            Price = 250m,
                            UpdatedAt = new DateTime(2026, 4, 4, 5, 54, 12, 437, DateTimeKind.Utc).AddTicks(6136)
                        },
                        new
                        {
                            Id = 3,
                            Category = "entrance",
                            CreatedAt = new DateTime(2026, 4, 4, 5, 54, 12, 437, DateTimeKind.Utc).AddTicks(6137),
                            Name = "Senior Ticket",
                            Price = 300m,
                            UpdatedAt = new DateTime(2026, 4, 4, 5, 54, 12, 437, DateTimeKind.Utc).AddTicks(6137)
                        },
                        new
                        {
                            Id = 4,
                            Category = "entrance",
                            CreatedAt = new DateTime(2026, 4, 4, 5, 54, 12, 437, DateTimeKind.Utc).AddTicks(6138),
                            Name = "VIP Ticket",
                            Price = 1000m,
                            UpdatedAt = new DateTime(2026, 4, 4, 5, 54, 12, 437, DateTimeKind.Utc).AddTicks(6138)
                        },
                        new
                        {
                            Id = 5,
                            Category = "donation",
                            CreatedAt = new DateTime(2026, 4, 4, 5, 54, 12, 437, DateTimeKind.Utc).AddTicks(6162),
                            Name = "Small Donation",
                            Price = 100m,
                            UpdatedAt = new DateTime(2026, 4, 4, 5, 54, 12, 437, DateTimeKind.Utc).AddTicks(6162)
                        },
                        new
                        {
                            Id = 6,
                            Category = "donation",
                            CreatedAt = new DateTime(2026, 4, 4, 5, 54, 12, 437, DateTimeKind.Utc).AddTicks(6163),
                            Name = "Medium Donation",
                            Price = 500m,
                            UpdatedAt = new DateTime(2026, 4, 4, 5, 54, 12, 437, DateTimeKind.Utc).AddTicks(6164)
                        },
                        new
                        {
                            Id = 7,
                            Category = "donation",
                            CreatedAt = new DateTime(2026, 4, 4, 5, 54, 12, 437, DateTimeKind.Utc).AddTicks(6165),
                            Name = "Large Donation",
                            Price = 1000m,
                            UpdatedAt = new DateTime(2026, 4, 4, 5, 54, 12, 437, DateTimeKind.Utc).AddTicks(6165)
                        },
                        new
                        {
                            Id = 8,
                            Category = "product",
                            CreatedAt = new DateTime(2026, 4, 4, 5, 54, 12, 437, DateTimeKind.Utc).AddTicks(6179),
                            Name = "Merchandise T-Shirt",
                            Price = 250m,
                            UpdatedAt = new DateTime(2026, 4, 4, 5, 54, 12, 437, DateTimeKind.Utc).AddTicks(6180)
                        },
                        new
                        {
                            Id = 9,
                            Category = "product",
                            CreatedAt = new DateTime(2026, 4, 4, 5, 54, 12, 437, DateTimeKind.Utc).AddTicks(6181),
                            Name = "Snack Pack",
                            Price = 150m,
                            UpdatedAt = new DateTime(2026, 4, 4, 5, 54, 12, 437, DateTimeKind.Utc).AddTicks(6181)
                        },
                        new
                        {
                            Id = 10,
                            Category = "product",
                            CreatedAt = new DateTime(2026, 4, 4, 5, 54, 12, 437, DateTimeKind.Utc).AddTicks(6182),
                            Name = "Beverage",
                            Price = 100m,
                            UpdatedAt = new DateTime(2026, 4, 4, 5, 54, 12, 437, DateTimeKind.Utc).AddTicks(6182)
                        });
                });

            modelBuilder.Entity("MultiBillGenerator.Models.BillItem", b =>
                {
                    b.HasOne("MultiBillGenerator.Models.Bill", "Bill")
                        .WithMany("Items")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("MultiBillGenerator.Models.Bill", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
